---

BINARY_DIR: /home/amaxwell/NIMS/build-nims

APPLICATIONS:
    - name: detector
      args:
        - "--help"
    - name: ingester
      args:
        - "--help"
    - name: tracker
      args:
        - "--help"
 

...