---

# default to the same dir as the config file
BINARY_DIR: .

# "name" is a path relative to BINARY_DIR
APPLICATIONS:
    - name: detector
      args:
    - name: ingester
      args:
          - -i
          - /tmp
    - name: tracker
      args:
 
# Need this here for python code.
FRAMEBUFFER_NAME: nims_framebuffer

# Define the type of sonar device connected to the system.
# 1 = M3 (that's all we support for now.)
SONAR_TYPE: 1

# Specific to M3
M3_HOST_ADDR: 130.20.41.25


...
