---

# files in /var/tmp will persist across reboots; this keeps
# us from cluttering up the binary directory
LOG_DIR: /var/tmp

# "name" is a path relative to the NIMS_HOME environment variable
APPLICATIONS:
    - name: ingester
      args:
          - -c
          - config.yaml
          - -l
          - debug
    - name: detector
      args:
          - -c
          - config.yaml
          - -l
          - debug
    - name: tracker
      args:
          - -c
          - config.yaml
          - -l
          - debug
 
# Need this here for python code.
FRAMEBUFFER_NAME: nims_framebuffer
TRACKER_NAME: nims_tracker
TRACKER_SOCKET_NAME: nims_tracker_socket

# Define the type of sonar device connected to the system.
# 1 = M3, 2 = BlueView, 3 = EK60
SONAR_TYPE: 1

# Used for M3, BlueView and EK60
SONAR_HOST_ADDR: 130.20.41.194 # shari's laptop
#SONAR_HOST_ADDR: 192.168.1.45 # shari's BlueView
#SONAR_HOST_ADDR: 130.20.85.189 # arm
# Used by EK60, no idea what this should be
SONAR_PORT: 20000
# Used by nims.py
WEB_SERVER_PORT: 8080

### TRACKER ###
TRACKER:
    num_pings_for_moving_avg : 50
    max_ping_gap_in_track    : 2
    min_pings_for_track      : 7
    threshold_in_stdevs      : 2.0
    min_target_size          : 4
    process_noise            : 0.1
    measurement_noise        : 0.001
    max_prediction_error     : 15
...
