---

# default to the same dir as the config file
BINARY_DIR: .

# files in /var/tmp will persist across reboots; this keeps
# us from cluttering up the binary directory
LOG_DIR: /var/tmp/NIMS/log

# "name" is a path relative to BINARY_DIR
APPLICATIONS:
    #- name: detector
      #args:
          #- -c
          #- config.yaml
          #- l
          #- debug
    - name: ingester
      args:
          - -c
          - config.yaml
          - l
          - debug
    - name: tracker
      args:
          - -c
          - config.yaml
          - l
          - debug
 
# Need this here for python code.
FRAMEBUFFER_NAME: nims_framebuffer

# Define the type of sonar device connected to the system.
# 1 = M3 (that's all we support for now.)
SONAR_TYPE: 1

# Specific to M3
M3_HOST_ADDR: 130.20.41.225

### TRACKER ###
TRACKER:
    num_pings_for_moving_avg : 10
    max_ping_gap_in_track    : 3
    min_pings_for_track      : 7
    threshold_in_stdevs      : 3
    process_noise            : 0.1
    measurement_noise        : 0.001
    max_prediction_error     : 15
...
