---

# default to the same dir as the config file
BINARY_DIR: .

# "name" is a path relative to BINARY_DIR
APPLICATIONS:
    - name: detector
      args:
    - name: ingester
      args:
          - -i
          - /tmp
    - name: tracker
      args:
 
FB_WRITER_QUEUE: /nims_framebufferwriter-connect

...