---

# files in /var/tmp will persist across reboots; this keeps
# us from cluttering up the binary directory
LOG_DIR: /var/tmp

# "name" is a path relative to the NIMS_HOME environment variable
APPLICATIONS:
    - name: ingester
      args:
          - -c
          - config.yaml
          - -l
          - debug
    - name: detector
      args:
          - -c
          - config.yaml
          - -l
          - debug
    - name: tracker
      args:
          - -c
          - config.yaml
          - -l
          - debug
    - name: tracks_server.py
      args:
        
 
# Need this here for python code.
FRAMEBUFFER_NAME: nims_framebuffer
TRACKER_NAME: nims_tracker
TRACKER_SOCKET_NAME: nims_tracker_socket

# Define the type of sonar device connected to the system.
# 1 = M3, 2 = BlueView, 3 = EK60
SONAR_TYPE: 3

# Used for M3, BlueView and EK60
SONAR_HOST_ADDR: 130.20.41.143 # triton laptop
#SONAR_HOST_ADDR: 130.20.41.194 # shari's laptop
#SONAR_HOST_ADDR: 192.168.1.45 # shari's BlueView
#SONAR_HOST_ADDR: 130.20.85.189 # arm

# Used for EK60 Sonar type
SONAR_EK60:
  # Ethernet Output dialog 
  sonar_port: 3000
  # Transducer parameters dialog
  along_sensitivity: 23.0
  along_offset: 0.0
  athwart_sensitivity: 23.0
  athwart_offset: 0.0
  # not sure where to get this, and if user settable
  along_beamwidth: 6.78
  athwart_beamwidth: 6.83

# Used by nims.py
WEB_SERVER_PORT: 8080

# track server for external clients
TRACKSERVER_SOCKET_PORT: 8001

### DETECTOR ###
DETECTOR:
    moving_avg_seconds       : 10
    threshold_in_stdevs      : 2.0
    min_target_size          : 6

# for extract_1.mmb, change min_target_size to 10
#
### TRACKER ###
TRACKER:
    max_gap_in_track_seconds : 1
    min_track_seconds        : 3
    process_noise            : 0.1
    measurement_noise        : 0.001
    max_prediction_error     : 15
...
